Apple clone branch
camfilho/old-apple-clone pull request #2
Opened 2019-09-24 19:46 UTC by camfilho

Branch ready to be sent to be reviewed by the TSAs.

2019-09-24 20:50 UTC, Forison reviewed
# Pull request under review by Addo

2019-09-24 21:14 UTC, Forison requested changes
Hi Carlos 👋
Here are a few changes to make in other to get this project approved.
- #### **[REQUIRED]** NAVBAR🙂
1. It should be made of nine different buttons with the Apple logo on the leftmost section and a search field on the rightmost section
> As it stands now the search has no input field and icon.
>  your nav links should be wrapped in anchor tag instead 
>  You can achieve the button effect by giving hover effect to the ```anchor``` tags and giving ```borders``` 
2. The navbar ought to have a background gradient implementation. [read](https://www.w3schools.com/css/css3_gradients.asp)

- #### **[REQUIRED]** project implementation🙂
1. Each Image in ```main``` have to be wrapped in an anchor tag so they redirect user upon clicking it
> images are added to a page by using ```img``` tag
2. Set the width of the ```.wrapper``` to 100%, to have filled the whole screen.

# Kindly make those changes and submit for review again
Happy coding

2019-09-24 21:48 UTC, Forison commented on index.html
> +                <div class="img-1"></div>
# use ```<img>``` tag for the image and wrap ```<a>``` around each image

2019-09-24 21:49 UTC, Forison commented on index.html
> +                <a href="#" class="img-3"></a>
# use ```<img>``` tag for the image and wrap ```<a>``` around each image

2019-09-24 21:50 UTC, Forison commented on index.html
> +                <div class="img-2"></div>
# use ```<img>``` tag for the image and wrap ```<a>``` around each image ```<a> <img> </a>````

2019-09-25 17:27 UTC, whiz25 approved these changes
## Awesome job :+1: @camfilho 
You did good. All checks have passed and all requirements met.
Please go ahead and merge. I wish you luck in your next projects.

2019-09-26 18:57 UTC, merged